// examples/react-app/src/js/pages/home.jsx
import React, { useState } from 'react';

export default function Home({ name }) {
  const [count, setCount] = useState(0);

  return (
    <div style={{
      fontFamily: 'system-ui, sans-serif',
      minHeight: '100vh',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      padding: '2rem'
    }}>
      <div style={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: '2rem'
      }}>
        <img src="/images/kemal.png" alt="Kemal" width="80" height="80" />
        <span style={{ fontSize: '2rem', fontWeight: 'bold', margin: '0 1rem', color: '#ccc' }}>+</span>
        <img src="/images/inertia.png" alt="Inertia" width="80" height="80" />
        <span style={{ fontSize: '2rem', fontWeight: 'bold', margin: '0 1rem', color: '#ccc' }}>+</span>
        <img src="/images/react.png" alt="React" width="80" height="80" />
      </div>

      <h1 style={{ marginBottom: '1rem' }}>Hello from {name}!</h1>

      <div className="card">
        <p className="counter-text">
          Counter: <span className="count-value">{count}</span>
        </p>
        <button 
          onClick={() => setCount(count + 1)}
          className="btn-primary"
        >
          Increment
        </button>
      </div>

      <style>{`
        .card {
          margin-top: 2rem;
          padding: 2rem;
          background: white;
          border-radius: 12px;
          text-align: center;
          min-width: 240px;
        }

        .counter-text {
          font-size: 1.25rem;
          color: #374151;
          margin-bottom: 1.5rem;
        }

        .count-value {
          font-weight: 800;
          color: #007bff;
          font-size: 1.5rem;
        }

        .btn-primary {
          padding: 0.75rem 1.5rem;
          background: #007bff;
          color: white;
          border: none;
          border-radius: 8px;
          cursor: pointer;
          font-weight: 600;
          font-size: 1rem;
          transition: all 0.2s;
        }

        .btn-primary:hover {
          background: #0056b3;
        }
      `}</style>
    </div>
  );
}

// examples/svelte-app/src/js/Pages/Home.svelte
<script>
  export let name;
  let count = 0;
</script>

<div
  style="font-family: system-ui, sans-serif; min-height: 100vh; display: flex; flex-direction: column; align-items: center; justify-content: center; padding: 2rem;"
>
  <div
    style="display: flex; align-items: center; justify-content: center; margin-bottom: 2rem;"
  >
    <img src="/images/kemal.png" alt="Kemal" width="80" height="80" />
    <span
      style="font-size: 2rem; font-weight: bold; margin: 0 1rem; color: #ccc;"
      >+</span
    >
    <img src="/images/inertia.png" alt="Inertia" width="80" height="80" />
    <span
      style="font-size: 2rem; font-weight: bold; margin: 0 1rem; color: #ccc;"
      >+</span
    >
    <img src="/images/svelte.png" alt="Svelte" width="80" height="80" />
  </div>

  <h1 style="margin-bottom: 1rem;">Hello from {name}!</h1>

  <div class="card">
    <p class="counter-text">
      Counter: <span class="count-value">{count}</span>
    </p>
    <button on:click={() => (count += 1)} class="btn-primary">
      Increment
    </button>
  </div>
</div>

<style>
  .card {
    margin-top: 2rem;
    padding: 2rem;
    background: white;
    text-align: center;
    min-width: 240px;
  }

  .counter-text {
    font-size: 1.25rem;
    color: #374151;
    margin-bottom: 1.5rem;
  }

  .count-value {
    font-weight: 800;
    color: #ff3e00;
    font-size: 1.5rem;
  }

  .btn-primary {
    padding: 0.75rem 1.5rem;
    background: #ff3e00;
    color: white;
    border: none;
    border-radius: 8px;
    cursor: pointer;
    font-weight: 600;
    font-size: 1rem;
    transition: all 0.2s;
    box-shadow: 0 2px 4px rgba(255, 62, 0, 0.2);
  }

  .btn-primary:hover {
    background: #e63800;
  }

  .btn-primary:active {
    transform: translateY(0);
  }
</style>
